'use client';
import { Cairo } from 'next/font/google';
import './globals.css';
import ToastContainerWrapper from '@/Components/Toast/Toast';
import { usePathname } from 'next/navigation';
import Navbar from '@/Components/Navbar/Navbar';
import Footer from '@/Components/Footer/Footer';
const cairoFont = Cairo({
  variable: '--font-Cairo',
  subsets: ['latin'],
});

<<<<<<< HEAD
=======

export const metadata = {
  title: "Baby Tracker",
  description: "Generated by create next app",
};

>>>>>>> b01bcd9010e8ae7a6d58a0500e52c4e52990df61
export default function RootLayout({ children }) {
  let pathname = usePathname();
  const hiddenRoutes = [
    '/signin',
    '/forget-password',
    '/logout',
    '/404',
    '/not-found',
  ];

  const shouldHideComponents = hiddenRoutes.includes(pathname);

  return (
    <html lang="en">
      <body className={`${cairoFont.variable}`}>
        <ToastContainerWrapper />
        {!shouldHideComponents && <Navbar />}
        {children}
        {!shouldHideComponents && <Footer />}
      </body>
    </html>
  );
}
