import { Cairo } from "next/font/google";
import "./globals.css";

const cairoFont = Cairo({
  variable: "--font-Cairo",
  subsets: ["latin"],
});


export const metadata = {
  title: "Baby Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${cairoFont.variable}`}>

        {children}
      </body>
    </html>
  );
}

